### ISSUE TITLE
Complex Deflines

### ISSUE THREAD

**Issue by deannachurch** [brentp/pyfasta#16]
I have a (large) fasta file that has deflines that look like this:

```
>gi|512322365|gb|CM001609.2| Homo sapiens chromosome 1, whole genome shotgun sequence
>gi|512322340|gb|CM001618.2| Homo sapiens chromosome 10, whole genome shotgun sequence
```

I was able to parse OK following your example:

```
from pyfasta import Fasta
f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])
print f.keys()

['CM001619.2', 'CM001630.2', 'CM001618.2', 'CM001617.2', 'CM001614.2', 'CM001624.2', 'CM001625.2', 'CM001615.2', 'CM001628.2', 'CM001613.2', 'CM001612.2', 'CM001629.2', 'CM001609.2', 'CM001623.2', 'CM001631.2', 'CM001622.2', 'CM001621.2', 'CM001611.2', 'CM001610.2', 'CM001620.2', 'CM001616.2', 'CM001626.2', 'CM001627.2']
```

But, then, trying to retrieve sequence by one of these keys failed

```
f["CM001619.2"][63846]

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-48-ee1290b34437> in <module>()
----> 1 f["CM001619.2"][63846]

/usr/local/lib/python2.7/site-packages/pyfasta/fasta.pyc in __getitem__(self, i)
    106         # this implements the lazy loading
    107         if self.key_fn is not None:
--> 108             i = self.key_fn(i)
    109         if i in self.chr:
    110             return self.chr[i]

<ipython-input-41-8d1e26fe8cf0> in <lambda>(key)
      1 from pyfasta import Fasta
----> 2 f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])
      3 print f.keys()

IndexError: list index out of range
```

Only using the full def-line worked

```
f["gi|512322365|gb|CM001609.2| Homo sapiens chromosome 1, whole genome shotgun sequence"][63846]

'G'
```

I am new to python and would believe I'm doing something wrong here, but my impression was that using the keys function would let me address the sequence using that key.

**Comment by brentp** [comment]
this is a limitation of the implementation. try deleting AssemblyInfo/CHM1_1.1.fa.flat
and the re-run

``` Python

f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])

```

it doesn't know to re-create the index if you change the key.

**Comment by brentp** [comment]
actually, there was a big problem handling key_fn. Now the problem is smaller and  your case should work. (It may require  you to remove the .gdx or .flat files.) Let me know if it solves your issue.

I'm leaving the issue open so that I'll eventually fix the problem with not re-indexing with changes on the key_fn.

**Comment by deannachurch** [comment]
Hi-
Thanks for the quick response- but I think there is still an issue. 
I removed the .gdx and .flat files and then ran this:

```
from pyfasta import Fasta
f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])
print f.keys()
f["CM001619.2"][63846]
```

with this output

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-49-0976a686ea1b> in <module>()
      2 f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])
      3 print f.keys()
----> 4 f["CM001619.2"][63846]

/usr/local/lib/python2.7/site-packages/pyfasta/fasta.pyc in __getitem__(self, i)
    106     def __iter__(self):
    107         return iter(self.index)
--> 108 
    109     def __getitem__(self, i):
    110         if i in self.chr:

<ipython-input-49-0976a686ea1b> in <lambda>(key)
      1 from pyfasta import Fasta
----> 2 f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])
      3 print f.keys()
      4 f["CM001619.2"][63846]

IndexError: list index out of range

['CM001619.2', 'CM001630.2', 'CM001618.2', 'CM001617.2', 'CM001614.2', 'CM001624.2', 'CM001625.2', 'CM001615.2', 'CM001628.2', 'CM001613.2', 'CM001612.2', 'CM001629.2', 'CM001609.2', 'CM001623.2', 'CM001631.2', 'CM001622.2', 'CM001621.2', 'CM001611.2', 'CM001610.2', 'CM001620.2', 'CM001616.2', 'CM001626.2', 'CM001627.2']
```

For now, I"ll just re-write the defline - which isn't that hard. 
thanks for the help!

**Comment by brentp** [comment]
did you update and re-install? I did make a change after my initial comment suggesting you remove the .gdx file, that should fix things for you. If not, please send an example fasta

**Comment by deannachurch** [comment]
Sorry- I forgot to mention that I did update (pip install --upgrade pyfasta) and then re-ran the code (in an ipython noteboook). 

The fasta is big, but I made it by taking chr*.fa.gz files from here:
ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/CHM1_1.1/Primary_Assembly/assembled_chromosomes/FASTA/

I gunzipped and than catted them together to make one big file.

**Comment by brentp** [comment]
hmm, did you restart the notebook kernel? I don't understand how that's happening still.

**Comment by deannachurch** [comment]
I hadn't thought about restarting the kernel- I just did that- and it works great. Thanks for the quick fix!

```
:

from pyfasta import Fasta
f = Fasta('AssemblyInfo/CHM1_1.1.fa', key_fn=lambda key: key.split("|")[3])
print f.keys()
f["CM001619.2"][63846]
['CM001619.2', 'CM001630.2', 'CM001618.2', 'CM001609.2', 'CM001631.2', 'CM001614.2', 'CM001624.2', 'CM001625.2', 'CM001615.2', 'CM001628.2', 'CM001613.2', 'CM001612.2', 'CM001629.2', 'CM001623.2', 'CM001622.2', 'CM001621.2', 'CM001611.2', 'CM001617.2', 'CM001610.2', 'CM001620.2', 'CM001616.2', 'CM001626.2', 'CM001627.2']
Out[1]:
u'N'
```

**Comment by deannachurch** [comment]
Hi Brent-
I'm still having some problems that I don't quite understand. I updated pyfasta:

```
pip install --upgrade pyfasta
Requirement already up-to-date: pyfasta in /usr/local/lib/python2.7/site-packages
Cleaning up...
```

This is a different fasta with more complex deflines:

> chr1  AC:CM000663.1  gi:224384768  LN:249250621  rl:Chromosome  M5:d949d5ece55a7f11abb62abfe947815d  AS:GRCh37.p13

The I parse like:

```
from pyfasta import Fasta
f = Fasta('AssemblyInfo/GCA_000001405_14_try2.fa', key_fn=lambda key: key.split()[1].replace("AC:", ""))
sorted(f.keys())
```

['AJ507799.2',
 'CM000663.1',
 'CM000664.1',
 'CM000665.1',
...
]

This looks exactly like the output I used on the previous fasta index, but the function to get the key is a bit more complex (adding in the replace to strip the AC:)

But, when I try to access the sequence:

```
 print f["CM000664.1"][10]
```

I get a TypeError:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-1a5840eb27de> in <module>()
     15         rec.CHROM = name2gb[rec.CHROM]
     16         print "%s\t%d" %(rec.CHROM, rec.POS)
---> 17         print f["CM000664.1"][10]
     18         #fa_ref = f[seqid][rec.POS]

TypeError: string indices must be integers, not str

I have tried deleting .flat, and .gdx and re-indexing (after restarting the ipython notebook kernal) but I still seem to be failing here. 
Sorry to bother you if this is my bug and not yours, but the only think I'm doing different from the first script that used this is the function call to index the fasta.

**Comment by brentp** [comment]
can you do "print f" before line 17? It seems to think that _f_ is a string and not a Fasta object.
Can you send an entire example, like this one:

``` Python
import pyfasta
print pyfasta

with open('t.fa', 'w') as fh:
    print >>fh, """
> chr1 AC:CM000663.1 gi:224384768 LN:249250621 rl:Chromosome M5:d949d5ece55a7f11abb62abfe947815d AS:GRCh37.p13
ACGCGACGCGACGCGACGCGACGCGACGCG
> chr1 AC:CM000623.1 gi:224384768 LN:249250621 rl:Chromosome M5:d949d5ece55a7f11abb62abfe947815d AS:GRCh37.p13
ACGCGACGCGACGCGACGCGACGCGACGCG
"""

f = pyfasta.Fasta('t.fa', key_fn=lambda key: key.split()[1].replace("AC:", ""))
print f.keys()

print f["CM000663.1"][10]
print f["CM000623.1"][10]

```

**Comment by deannachurch** [comment]
Ah- sorry to bother you. This is not your bug, but mine. 

```
from pyfasta import Fasta
f = Fasta('AssemblyInfo/GCA_000001405_14_try2.fa', key_fn=lambda key: key.split()[1].replace("AC:", ""))
sorted(f.keys())
print f["CM000663.1"][10000]
```

works
T

I must define f somewhere else in the script and I'm not seeing it. 

Again- sorry to bother and thanks for your patience and quick responses!
