### ISSUE TITLE
handling of fasta with duplicate entries

### ISSUE THREAD

**Issue by tanghaibao** [brentp/pyfasta#2]
consider the following fasta file,

<pre>
>a
aaa
>a
aaa
>c
ccc
>t
ttt
</pre>

extractions fail to give correct results, even for accessions that are unique

<pre>
$ pyfasta extract --header a --fasta t.fa
>a
ttt
$ pyfasta extract --header c --fasta t.fa
>c
ttt
</pre>

possible solutions are to issue warnings for duplicate entries ( like <code>Bio.SeqIO.index()</code> ), or fix this (preferrably)

**Comment by brentp** [comment]
this case will now raise an exception when first indexing. you will have to delete the .gdx and .flat files for it to take effect.
https://github.com/brentp/pyfasta/commit/f3c1208e8b2f376151026ec2fec394d62fcb9332
thanks for test case.
