### ISSUE TITLE
Writing FASTA files

### ISSUE THREAD

**Issue by rmzelle** [brentp/pyfasta#21]
Sorry if I missed it, but can pyfasta write FASTA files?

I have a genome FASTA file for which I would like to change the sequence of one of its scaffolds. After parsing the file with pyfasta and making this change, is there an easy way to write "f" (see below) to a FASTA file again?

```
>>> from pyfasta import Fasta
>>> f = Fasta('tests/data/three_chrs.fasta')
```

**Comment by brentp** [comment]
No, it's pretty much read-only. Though it's easy enough to write the modified sequence to the file yourself.
Also I recommend to use pyfaidx: https://github.com/mdshw5/pyfaidx

**Comment by rmzelle** [comment]
Okay, thanks for the tip. I decided to use http://biopython.org/wiki/SeqIO, which worked as well.
