### ISSUE TITLE
Clarify whether you use 1 or 0 based indexing and semi open/closed intervals

### ISSUE THREAD

**Issue by jamescasbon** [brentp/pyfasta#3]
Slicing and using the sequence method seem to expect 0/1 based indexing and return semi open/closed intervals.  You should clarify this in the documentation: 

```
In [62]: dna.GENOME['chr22'][17178570:17178572]
Out[62]: 'GG'

In [63]: dna.GENOME.sequence({'start':17178570,'stop':17178572, 'chr':'chr22'})
Out[63]: 'AGG'
```

**Comment by brentp** [comment]
Yes, this should be more explicit. Note that in the README.rst it has:

``` python
# can query by a 'feature' dictionary
>>> f.sequence({'chr': 'chr1', 'start': 2, 'stop': 9})
'CTGACTGA'

# same as:
>>> f['chr1'][1:9]
'CTGACTGA'
```

I see you have forked. If you add a better description, I will be happy to pull.

**Comment by brentp** [comment]
fixed by jamescasbon and uploaded to pypi (http://pypi.python.org/pypi/pyfasta/0.4.3)
